# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hsharame <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/24 18:14:09 by hsharame          #+#    #+#              #
#    Updated: 2024/07/15 12:42:18 by hsharame         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
FLAGS = -Wall -Wextra -Werror
SRC = ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c ft_isascii.c \
      ft_isdigit.c ft_isprint.c ft_itoa.c ft_memchr.c ft_memcmp.c ft_memcpy.c \
      ft_memmove.c ft_memset.c ft_putchar_fd.c ft_putendl_fd.c ft_putstr_fd.c \
      ft_split.c ft_strchr.c ft_strdup.c ft_striteri.c ft_strjoin.c \
      ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strmapi.c ft_strncmp.c \
      ft_strnstr.c ft_strrchr.c ft_strtrim.c ft_substr.c ft_tolower.c \
      ft_toupper.c ft_putnbr_fd.c ft_pdiu.c ft_printf.c ft_print_hex.c
HEAD = libft.h ft_printf.h
OBJS = ft_atoi.o ft_bzero.o ft_calloc.o ft_isalnum.o ft_isalpha.o ft_isascii.o \
      ft_isdigit.o ft_isprint.o ft_itoa.o ft_memchr.o ft_memcmp.o ft_memcpy.o \
      ft_memmove.o ft_memset.o ft_putchar_fd.o ft_putendl_fd.o ft_putstr_fd.o \
      ft_split.o ft_strchr.o ft_strdup.o ft_striteri.o ft_strjoin.o \
      ft_strlcat.o ft_strlcpy.o ft_strlen.o ft_strmapi.o ft_strncmp.o \
      ft_strnstr.o ft_strrchr.o ft_strtrim.o ft_substr.o ft_tolower.o \
      ft_toupper.o ft_putnbr_fd.o ft_pdiu.o ft_printf.o ft_print_hex.o
OPTION = -c -I $(HEAD)

all: $(NAME)

$(NAME): 
	cc $(FLAGS) $(OPTION) $(SRC)
	ar rc $(NAME) $(OBJS)
	ranlib $(NAME)

%.o: %.c
	cc $(FLAGS) -c $< -o $@ -I .

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
